--Criar role
CREATE ROLE localdb WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  BYPASSRLS
  PASSWORD 'db97!#!!';

--Criar banco WEB
CREATE DATABASE localdbwvwebprd
    WITH
    OWNER = localdb
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Criar banco APP
CREATE DATABASE localdbwvappprd
    WITH
    OWNER = localdb
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Alterar schema
ALTER SCHEMA public RENAME TO localdb;

-- Dados teste
INSERT INTO TMPINTEMPRESA (CDEMPRESA,NMEMPRESA,FLATIVO)
VALUES ('99999','EMPRESA TESTE','S');
INSERT INTO TMPINTREPRESENTANTE (CDREPRESENTANTE,NMREPRESENTANTE,FLTIPOCADASTRO,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','TESTE','R','S','I');
INSERT INTO TMPINTREPRESENTANTEEMP (CDEMPRESA,CDREPRESENTANTE,FLDEFAULT,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','99999','S','S','I');
INSERT INTO TMPINTTIPOPEDIDO (CDEMPRESA,CDREPRESENTANTE,CDTIPOPEDIDO,DSTIPOPEDIDO,FLATIVO)
VALUES ('99999','0','99999','TESTE','S');
INSERT INTO TMPINTCONDICAOPAGAMENTO (CDEMPRESA,CDREPRESENTANTE,CDCONDICAOPAGAMENTO,DSCONDICAOPAGAMENTO,FLATIVO)
VALUES ('99999','0','99999','TESTE','S');
INSERT INTO TMPINTTIPOPAGAMENTO (CDEMPRESA,CDREPRESENTANTE,CDTIPOPAGAMENTO,DSTIPOPAGAMENTO,FLATIVO)
VALUES ('99999','0','99999','TESTE','S');
INSERT INTO TMPINTCLIENTE (CDEMPRESA,CDREPRESENTANTE,CDCLIENTE,NMRAZAOSOCIAL,NMFANTASIA,CDCONDICAOPAGAMENTO,CDTIPOPAGAMENTO,CDTIPOPEDIDO,CDTABELAPRECO,NUCNPJ,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','99999','99999','TESTE RAZAO','TESTE FANTASIA','99999','99999','99999','99999','85267175000112','S','I');
INSERT INTO TMPINTFICHAFINANCEIRA (CDEMPRESA,CDCLIENTE,CDREPRESENTANTE,VLSALDOCLIENTE,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','99999','99999',99999,'S','I');
INSERT INTO TMPINTGRUPOPRODUTO1(CDGRUPOPRODUTO1,DSGRUPOPRODUTO1,FLATIVO,FLTIPOALTERACAO)
VALUES('99999','TESTE','S','I');
INSERT INTO TMPINTPRODUTO (CDEMPRESA,CDREPRESENTANTE,CDPRODUTO,DSPRODUTO,CDGRUPOPRODUTO1,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','0','99999','PRODUTO TESTE','99999','S','I');
INSERT INTO TMPINTESTOQUE (CDEMPRESA,CDREPRESENTANTE,CDPRODUTO,CDITEMGRADE1,CDITEMGRADE2,CDITEMGRADE3,CDLOCALESTOQUE,FLORIGEMESTOQUE,QTESTOQUE,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','0','99999','0','0','0','0','E',99999,'S','I');
INSERT INTO TMPINTTABELAPRECO (CDEMPRESA,CDREPRESENTANTE,CDTABELAPRECO,DSTABELAPRECO,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','0','99999','TABELA TESTE','S','I');
INSERT INTO TMPINTITEMTABELAPRECO (CDEMPRESA,CDREPRESENTANTE,CDTABELAPRECO,CDPRODUTO,CDUF,CDITEMGRADE1,CDITEMGRADE2,CDITEMGRADE3,CDUNIDADE,QTITEM,CDPRAZOPAGTOPRECO,VLUNITARIO,FLATIVO,FLTIPOALTERACAO)
VALUES ('99999','0','99999','99999','0','0','0','0','0','0','0',10,'S','I');