CREATE VIEW TBINTPEDIDOPENDENCIAPERM AS 
SELECT DISTINCT
	EMP.CDEMPRESA,
	USU.CDUSUARIO,
	MOT.CDMOTIVOPENDENCIA,
	'1'::NUMERIC(9) AS NUNIVELLIBERACAO
FROM TBLVWEMPRESA EMP
JOIN TBWMWUSUARIO USU ON USU.CDFUNCAO IN('ADMIN','EXPERT')
JOIN TBLVWMOTIVOPENDENCIA MOT ON 1=1
WHERE
	USU.FLATIVO='S'
AND EMP.FLATIVO='S'
AND MOT.FLATIVO='S';

CREATE VIEW TBINTTIPOFRETE AS
SELECT 
	CDEMPRESA,
	'0'::VARCHAR(20) AS CDREPRESENTANTE,
	'C'::VARCHAR(20) AS CDTIPOFRETE,
	'0'::VARCHAR(20) AS CDUF,
	'CIF'::VARCHAR(100) AS DSTIPOFRETE,
	'N'::CHAR(1) AS FLFRETEFOB,
	'S'::CHAR(1) AS flTipoFreteCif
FROM TBLVWEMPRESA
WHERE FLATIVO='S'
UNION 
SELECT 
	CDEMPRESA,
	'0'::VARCHAR(20) AS CDREPRESENTANTE,
	'F'::VARCHAR(20) AS CDTIPOFRETE,
	'0'::VARCHAR(20) AS CDUF,
	'FOB'::VARCHAR(100) AS DSTIPOFRETE,
	'S'::CHAR(1) AS FLFRETEFOB,
	'N'::CHAR(1) AS flTipoFreteCif
FROM TBLVWEMPRESA
WHERE FLATIVO='S'